# Generated by Django 2.1.1 on 2019-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190413_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
