# Generated by Django 2.1.1 on 2019-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
