# Generated by Django 2.1.1 on 2019-05-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20190505_1937'),
        ('home', '0004_order_price'),
    ]

    operations = [
    ]
