# Generated by Django 2.1.1 on 2019-05-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20190505_1938'),
        ('home', '0005_auto_20190505_2015'),
    ]

    operations = [
    ]
