# Generated by Django 2.1.1 on 2019-05-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_category_to_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
