# Generated by Django 2.1.1 on 2019-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
