# Generated by Django 2.1.1 on 2019-05-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190508_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
