# Generated by Django 2.1.1 on 2019-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190509_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
