# Generated by Django 2.1.1 on 2019-05-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_order_token'),
        ('home', '0021_auto_20190509_1610'),
    ]

    operations = [
    ]
